version: "3"

services:
    php:
        build: ./php
        volumes:
            - ./php/data:/var/www/html
        ports:
            - 8000:80
        image: php7.4-apache
        container_name: php7.4-login
    mysql:
        image: mysql:8.0
        volumes:
            - ./mysql/start:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=php1
            - MYSQL_PASSWORD=pjk-3kjf-Abc
        container_name: mysql8.0-login
